import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
        >
          <header className="relative flex items-center justify-center p-4 h-16 my-3">
            {/* <div className="absolute right-4 flex gap-2 sm:gap-3">
              <SignedOut>
                <SignInButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-9 px-3 sm:h-10 sm:px-4 hover:bg-[#5a3dd9] transition">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-9 px-3 sm:h-10 sm:px-4 hover:bg-[#5a3dd9] transition">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>

              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </div> */}

            {/* Centered NavBar */}
            <NavBar />
          </header>

          {/* Page content */}
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
